apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-app.yml --verbose
    kompose.version: 1.34.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.-router.entrypoints: web
    traefik.http.routers.-router.rule: Host(``)
    traefik.http.services.-service.loadbalancer.server.port: "3000"
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: app
