FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install --save openai
RUN npm install --save @nestjs/schedule

COPY . .

RUN npm install -g @nestjs/cli
RUN npm i --save-dev @types/node
RUN npm install --save @green-api/whatsapp-api-client 

RUN npm run build

FROM node:18-alpine

WORKDIR /app

RUN npm i --save-dev @types/node
RUN npm install -g @nestjs/cli

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "start:dev"]