services:
  app:
    image: ${REGISTRY}:${IMAGE_TAG}
    environment:
      NODE_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENV: production
      SUBDOMAIN: ${SUBDOMAIN}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_USER_GLOBAL: ${POSTGRES_USER_GLOBAL}
      POSTGRES_PASSWORD_GLOBAL: ${POSTGRES_PASSWORD_GLOBAL}
      POSTGRES_GLOBAL_DB_HOST: ${POSTGRES_GLOBAL_DB_HOST}
      POSTGRES_DB_GLOBAL: ${POSTGRES_DB_GLOBAL}
      POSTGRES_GLOBAL_DB_PORT: ${POSTGRES_GLOBAL_DB_PORT}
      ID_INSTANCE: ${ID_INSTANCE}
      API_TOKEN_INSTANCE: ${API_TOKEN_INSTANCE}
      OPEN_AI_TOKEN: ${OPEN_AI_TOKEN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ASSISTANT_ID: ${ASSISTANT_ID}
      RESEND_KEY: ${RESEND_KEY}
      DEEPSEEK_TOKEN: ${DEEPSEEK_TOKEN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SUBDOMAIN}-router.rule=Host(`${VIRTUAL_HOST}`)
      - traefik.http.routers.${SUBDOMAIN}-router.entrypoints=websecure
      - traefik.http.services.${SUBDOMAIN}-service.loadbalancer.server.port=3000
      - traefik.http.routers.${SUBDOMAIN}-router.tls=true
      - traefik.http.routers.${SUBDOMAIN}-router.tls.certresolver=myresolver
    networks:
      - app-network
    restart: unless-stopped
    container_name: ${SUBDOMAIN}-app
    # Health check simple - verificar proceso Node.js
    healthcheck:
      test: ["CMD", "pgrep", "-f", "node.*dist/main"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  app-network:
    external: true
