version: '3'
services:
  reverse-proxy:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ## APP
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: prod
      VIRTUAL_HOST: "app.whatsproy.com"
      VIRTUAL_PORT: 3000
      ENV: ${ENV}
    networks:
      - app-network

  ## DB
  db-global:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENV: ${ENV}
    volumes:
      - globaldb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app-network:
          aliases:
            - db-global

  ## NGINX server
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "81:81"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   networks:
  #     - app-network

networks:
  app-network:

volumes:
  globaldb-data:
