services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      NODE_ENV: dev
      VIRTUAL_HOST: app.whatsproy.com
      VIRTUAL_PORT: 3000
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PASS: ${EMAIL_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_GLOBAL_DB_HOST: ${POSTGRES_GLOBAL_DB_HOST}
      POSTGRES_GLOBAL_DB_PORT: ${POSTGRES_GLOBAL_DB_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CLIENT_EMAIL: ${GOOGLE_CLIENT_EMAIL}
      GOOGLE_PRIVATE_KEY: ${GOOGLE_PRIVATE_KEY}
      RESEND_KEY: ${RESEND_KEY}
      ENV: ${ENV}
      SUBDOMAIN: app
    networks:
      - app-network
  db-global:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENV: ${ENV}
    volumes:
      - globaldb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      app-network:
        aliases:
          - db-global
  works-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - .:/app
    environment:
      NODE_ENV: dev
      VIRTUAL_HOST: works.whatsproy.com
      VIRTUAL_PORT: 3000
      POSTGRES_USER: works_user
      POSTGRES_PASSWORD: works_pass
      POSTGRES_DB: db_works
      POSTGRES_USER_GLOBAL: ${POSTGRES_USER_GLOBAL}
      POSTGRES_PASSWORD_GLOBAL: ${POSTGRES_PASSWORD_GLOBAL}
      POSTGRES_DB_GLOBAL: ${POSTGRES_DB_GLOBAL}
      POSTGRES_GLOBAL_DB_HOST: ${POSTGRES_GLOBAL_DB_HOST}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      POSTGRES_GLOBAL_DB_PORT: ${POSTGRES_GLOBAL_DB_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ENV: ${ENV}
      SUBDOMAIN: works
      ID_INSTANCE: ${ID_INSTANCE}
      API_TOKEN_INSTANCE: ${API_TOKEN_INSTANCE}
    networks:
      - app-network
  works-db:
    image: postgres:13
    environment:
      POSTGRES_USER: works_user
      POSTGRES_PASSWORD: works_pass
      POSTGRES_DB: db_works
      ENV: ${ENV}
    volumes:
      - works-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      app-network:
        aliases:
          - works-db
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - app-network
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-network
    restart: always
networks:
  app-network:
volumes:
  globaldb-data:
  works-db-data:
