name: Deploy Single Company to PROD

on:
  workflow_dispatch:
    inputs:
      empresa_db_name:
        description: 'Nombre de subdominio de la empresa a deployar'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: prod

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Connect to Droplet
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        DROPLET_USER: ${{ secrets.DROPLET_USER }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no "${DROPLET_USER}@${DROPLET_IP}" 'mkdir -p /projects'

    - name: Execute Deployment Script for Single Company
      env:
        EMPRESA_DB_NAME: ${{ github.event.inputs.empresa_db_name }}
        POSTGRES_USER_GLOBAL: ${{ secrets.POSTGRES_USER_GLOBAL }}
        POSTGRES_PASSWORD_GLOBAL: ${{ secrets.POSTGRES_PASSWORD_GLOBAL }}
        POSTGRES_DB_GLOBAL: ${{ secrets.POSTGRES_DB_GLOBAL }}
        POSTGRES_GLOBAL_DB_HOST: ${{ secrets.POSTGRES_GLOBAL_DB_HOST }}
        POSTGRES_GLOBAL_DB_PORT: ${{ secrets.POSTGRES_GLOBAL_DB_PORT }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        OPEN_AI_TOKEN: ${{ secrets.OPEN_AI_TOKEN }}
        GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        TOKEN_CONNECT_GIT: ${{ secrets.TOKEN_CONNECT_GIT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_BUCKET: ${{ secrets.SUPABASE_BUCKET }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        RESEND_KEY: ${{ secrets.RESEND_KEY}}
        DEEPSEEK_TOKEN: ${{ secrets.DEEPSEEK_TOKEN }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      run: node deploySignleCompanyProd.js "$EMPRESA_DB_NAME"
